name: CI

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  shellcheck:
    name: ShellCheck Entrypoint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@2.0.0

  build-keymap:
    name: Local Keymap Build DZ65 RGB v3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          keyboard: dztech/dz65rgb/v3
          keymap: testing-keymap
          local-keymap-path: test-keymap/keymaps/testing-keymap

  build-keyboard:
    name: Local Keyboard Build DZ65 RGB v3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          keyboard: test-keyboard/dz65rgb/v3
          keymap: default
          local-keyboard-path: test-keyboard

  build-helios:
    name: Controller Build Corne for Helios
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          keyboard: crkbd/rev1
          keymap: default
          controller: helios